### ISSUE TITLE
Aim 2.2.a. Evaluate consistency of relation and entity types used within BioPortal ontologies.

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/BioPortal-to-KGX#22]
Specifically:
- [x] Get total counts of KGX validation error by type across all transforms (e.g., "X transforms have at least one error of type Y")
  - [x] Which transforms did not work?
  - [x] How many of those transformation issues are resolvable?
  - [x] How many of those transformation issues are not worth resolving *in this repository* (e.g., something structurally wrong with ontology on Bioportal; entry may be duplicated, test, or otherwise broken)
- [x] Enumerate usage of entity types by ontology (e.g., "X ontologies use biolink:OntologyClass)
- [x] Enumerate usage of relation types by ontology (e.g., "X ontologies use biolink:subclass_of)

**Comment by caufieldjh** [comment]
Output of newly added script `get_all_transform_stats.sh`:
```
All processed ontologies:
910
All successful JSON transforms:
896
All successful KGX TSV transforms:
888
Transforms with at least one of the following errors:
MISSING_NODE_PROPERTY
0
MISSING_EDGE_PROPERTY
0
INVALID_NODE_PROPERTY
833
INVALID_EDGE_PROPERTY
796
INVALID_NODE_PROPERTY_VALUE_TYPE
28
INVALID_NODE_PROPERTY_VALUE
833
INVALID_EDGE_PROPERTY_VALUE_TYPE
0
INVALID_EDGE_PROPERTY_VALUE
796
MISSING_CATEGORY
0
INVALID_CATEGORY
888
Category 'OntologyClass' is a mixin in the Biolink Model
888
MISSING_EDGE_PREDICATE
0
INVALID_EDGE_PREDICATE
495
MISSING_NODE_CURIE_PREFIX
0
DUPLICATE_NODE
0
MISSING_NODE
0
INVALID_EDGE_TRIPLE
0
VALIDATION_SYSTEM_ERROR
0
```

The big take-home here is that entities in every transform gets assigned `biolink:OntologyClass` despite [Biolink modeling `OntologyClass` as a class mixin](https://biolink.github.io/biolink-model/docs/OntologyClass.html#class-ontologyclass) rather than intending it to be a class type itself. 

Do we know enough about each ontology to assign a mode specific class to nodes?

There are other metaclasses, like `[biolink:TaxonomicRank](https://w3id.org/biolink/vocab/TaxonomicRank)` - these may still make sense to use in some contexts.

**Comment by caufieldjh** [comment]
Finding appropriate mappings vs. Biolink is a goal for `kgx` - that will help to reduce the number of OntologyClass nodes.

**Comment by caufieldjh** [comment]
Completely failed transforms:
| ID               | Name                                                       | Issue                                                          |
|------------------|------------------------------------------------------------|----------------------------------------------------------------|
| NIFSTD           | Neuroscience Information Framework (NIF) Standard Ontology | Unknown                                                        |
| EXACT            | An ontology for experimental actions                       | Small, alpha status, last uploaded 2014                        |
| DOID             | Human Disease Ontology                                     | Unknown - would really expect this to work                     |
| ECOCORE          | An ontology of core ecological entities                    | Error in Bioportal? Last updated Mar 10 2022                   |
| ETHIOPIADISEASES | EthiopiaDiseaseList                                        | Multiple versions? Does not render on Bioportal                |
| LC-CARRIERS      | Library of Congress Carriers Scheme                        | In SKOS format; does not render on Bioportal                   |
| SCDO             | Sickle Cell Disease Ontology                               | Unknown                                                        |
| FENICS           | Functional Epilepsy Nomenclature for Ion Channels          | Using webprotege: prefix (unsure if related to transform fail) |
| FOVT             | FuTRES Ontology of Vertebrate Traits                       | Unknown                                                        |
| PTRANS           | Pathogen Transmission Ontology                             | Does not render on Bioportal                                   |
| TIMEBANK         | Timebank Ontology                                          | Unknown                                                        |
| GSSO             | Gender, Sex, and Sexual Orientation Ontology               | Unknown                                                        |
| CST              | Cancer Staging Terms                                       | Does not render on Bioportal                                   |

**Comment by caufieldjh** [comment]
See #23 for `Unknown CURIE prefix: file` issue.

**Comment by caufieldjh** [comment]
With issues #15 and #23 resolved, the only remaining problematic transforms are:
* ECOCORE 
* ETHIOPIADISEASES 
* LC-CARRIERS
* CST 
* MARC-RELATORS

**Comment by caufieldjh** [comment]
ECOCORE has a new version on BioPortal - can just use this for now:
https://bioportal.bioontology.org/ontologies/ECOCORE/?p=summary

Can drop LC-CARRIERS and MARC-RELATORS.

**Comment by jvendetti** [comment]
Hi Harry.

**ETHIOPIADISEASES**

The latest submission in our system was corrupt. I recreated/reprocessed the submission so that the ontology is accessible again:

https://bioportal.bioontology.org/ontologies/ETHIOPIADISEASES?p=summary

**CST**

It looks like the end user uploaded an ontology source file for this entry, but we were never able to load the data into the triplestore, because our code errors out when we try to serialize to RDF/XML format with the following error:

```
org.semanticweb.owlapi.rdf.rdfxml.renderer.IllegalElementNameException: Illegal Element Name (Element Is Not A QName): http://www.w3.org/2000/01/rdf-schema#comment:
```

I think this one could probably be dropped for now.

**Comment by caufieldjh** [comment]
Great - thanks @jvendetti !

**Comment by jvendetti** [comment]
Hi @caufieldjh. It turns out that the maintainers of ETHIOPIADISEASE told John that they no longer need this entry in BioPortal. I had originally reprocessed it, but I've now deleted the entry.

**Comment by caufieldjh** [comment]
Great, thanks! One more off the list.

**Comment by caufieldjh** [comment]
Updated statistics, including for types:
```
*** General ontology counts:
All processed ontologies:       910
All successful JSON transforms: 906
All successful KGX TSV transforms:      903
All transforms with KGX validation logs:        902
All transforms with ROBOT measure reports:      883
All transforms with ROBOT validation reports:   904
Ontologies with failed transforms:      
./transformed/ontologies/ETHIOPIADISEASES
./transformed/ontologies/LC-CARRIERS
./transformed/ontologies/CST
*** Transforms with at least one of the following errors:
MISSING_NODE_PROPERTY   0
MISSING_EDGE_PROPERTY   0
INVALID_NODE_PROPERTY   844
INVALID_EDGE_PROPERTY   807
INVALID_NODE_PROPERTY_VALUE_TYPE        31
INVALID_NODE_PROPERTY_VALUE     844
INVALID_EDGE_PROPERTY_VALUE_TYPE        0
INVALID_EDGE_PROPERTY_VALUE     807
MISSING_CATEGORY        0
INVALID_CATEGORY        902
Category 'OntologyClass' is a mixin in the Biolink Model        902
MISSING_EDGE_PREDICATE  0
INVALID_EDGE_PREDICATE  502
MISSING_NODE_CURIE_PREFIX       0
DUPLICATE_NODE  0
MISSING_NODE    0
INVALID_EDGE_TRIPLE     0
VALIDATION_SYSTEM_ERROR 0
*** Node type counts:
biolink:NamedThing      731
biolink:OntologyClass   903
biolink:BiologicalProcess       76
biolink:Cell    110
biolink:CellularComponent       46
biolink:ChemicalSubstance       119
biolink:Disease 15
biolink:Event   2
biolink:ExposureEvent   3
biolink:Gene    9
biolink:MolecularActivity       49
biolink:NamedThing      731
biolink:OntologyClass   903
biolink:OrganismalEntity        128
biolink:Pathway 6
biolink:PhenotypicFeature       44
biolink:Protein 79
biolink:SequenceFeature 56
biolink:SexQualifier    1
biolink:Source  2
biolink:TaxonomicRank   3
biolink:Unit    2
biolink:AnatomicalEntity        112
*** Edge type counts (i.e., predicate types):
biolink:related_to      376
biolink:subclass_of     899
biolink:part_of 52
biolink:inverseOf       408
biolink:subPropertyOf   449
biolink:has_part        165
biolink:has_participant 99
biolink:has_unit        29
biolink:preceded_by     69
biolink:has_attribute   76
biolink:positively_regulates    35
biolink:negatively_regulates    37
```
This includes all node types across all ontologies, and a selection of the more common predicate types.

**Comment by caufieldjh** [comment]
Closing issue as complete - reopen as needed
