### ISSUE TITLE
Convert prefix conversion to use `curies` package

### ISSUE THREAD

**Issue by caufieldjh** [ncbo/BioPortal-to-KGX#67]
The `curies` package c/o @cthoyt should be able to more elegantly convert prefixes to CURIEs.

See https://github.com/cthoyt/curies

Example:
```
converter = Converter.from_reverse_prefix_map({

    "http://purl.obolibrary.org/obo/CHEBI_": "CHEBI",

    "https://www.ebi.ac.uk/chebi/searchId.do?chebiId=": "CHEBI",

    "http://purl.obolibrary.org/obo/MONDO_": "MONDO",

})

converter.expand("CHEBI:138488")
'http://purl.obolibrary.org/obo/CHEBI_138488'

converter.compress("http://purl.obolibrary.org/obo/CHEBI_138488")
'CHEBI:138488'

converter.compress("https://www.ebi.ac.uk/chebi/searchId.do?chebiId=138488")
'CHEBI:138488'
```

**Comment by cthoyt** [comment]
happy to accept suggestions/PRs for extra utilities in this package, too, as long as they're general!

**Comment by caufieldjh** [comment]
Will implement `universalizer` here, which uses `curies`/Bioregistry prefixes. Any subsequent changes to node normalization will happen in `universalizer`.
